### ISSUE TITLE
Can MOFA integrate different omics data from independent studies?

### ISSUE THREAD

**Issue by ElyasMo** [bioFAM/MOFA2#100]
Thank you for developing such a great toolkit.

You have mentioned that "MOFA needs the multi-modal measurements to be derived from the same samples." Using MOFA , would it be possible to integrate the different types of omics data (e.g, transcriptomics, proteomics and metabolomics) which are captured independently in different studies from the same type of human disorder for instance?

In other words, is integrating different types of omics data which are measured independently in different studies possible using MOFA?

Regards
Elyas

**Comment by gtca** [comment]
Hey @ElyasMo, glad you find MOFA useful!

As a method, MOFA addresses joint analysis of feature sets (views) from the same _samples_ (individuals, cell types, single cells, etc.).
So the answer to your question depends on how you're going to aggregate the data. For instance, if you're going to consider omics measurements in different cell types across different studies, that fits the MOFA framework.

**Comment by rargelaguet** [comment]
Hi @ElyasMo, 

when integrating omics data across multiple studies is common to have sources of variability that are shared across studies vs individual to a specific study. To characterise the variability across groups of samples (in your case one group = one study) we implemented a multi-group framework. Here is an example of the multi-group framework using scRNA-seq data: https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/scRNA_gastrulation.html

Having said that, doing multi-modal and multi-group analysis at the same time is a bit complex. If you are not familiar with MOFA I would suggest you start the analysis just with multi-omics analysis.
