### ISSUE TITLE
batch effcts and data integration

### ISSUE THREAD

**Issue by wangjiawen2013** [bioFAM/MOFA2#107]
Hi,
There are various tools to perfrom batch effects removal or data integration in scRNAseq, such as CCA (seurat), scvi-tools, harmony, scanorama and so on. Can I use mofa/mofa2 for this purpose ? Is mofa/mofa2 an equivalence of these tools ?

**Comment by rargelaguet** [comment]
Hi @wangjiawen2013 ,
sorry for my very late reply, but MOFA should not be used for batch effect correction (i.e. horizontal data integration). The methods you mention are much better suited for this task. MOFA is a vertical integration method that is applicable when you have multi-omics from individual samples (or cells). 

Maybe our review on single-cell data integration clarifies some of this concepts: https://www.nature.com/articles/s41587-021-00895-7
