### ISSUE TITLE
Have samples that are missing some data modality

### ISSUE THREAD

**Issue by statwangz** [bioFAM/MOFA2#118]
Thank you for developing such great software.

I found that in your [tutorial](https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/getting_started_R.html) you said "It is fine if you have samples that are missing some data modality, but there has to be a significant degree of matched measurements". So I'm curious whether MOFA+ can be used for unpaired multi-omics single-cell data integration (also known as diagonal integration). For example, for group 1 we only have view 1 data and for group 2 we only have view 2 data.

Best regards,
Zhiwei

**Comment by rargelaguet** [comment]
Hi Zhiwei,
thanks for your kind words. MOFA is aimed at vertical integration. While it can cope with some samples missing entire data modalities, it cannot be used for diagonal integration. There are methods that have been developed to address this task, like GLUE (https://github.com/gao-lab/GLUE)

**Comment by statwangz** [comment]
> 

Thanks for the quick reply!

**Comment by statwangz** [comment]
> Hi Zhiwei, thanks for your kind words. MOFA is aimed at vertical integration. While it can cope with some samples missing entire data modalities, it cannot be used for diagonal integration. There are methods that have been developed to address this task, like GLUE (https://github.com/gao-lab/GLUE)

Sorry that I'm still confused why MOFA cannot be used for multi groups analysis. Could you give me some insights from the statistics view? In my opinion, GLUE incorporates feature regulation information to guide the direction of dimensionality reduction for distinct groups.

**Comment by rargelaguet** [comment]
It can certainly be used for both multi-group and multi-view analysis. We have [a tutorial demonstrating multi-group analysis using scRNA-seq data](https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/scRNA_gastrulation.html). But you need some degree of overlap in the observations between groups and data modalities. MOFA doesn't work when one group of samples only has only modality 1 and the other group of samples has only modality 2.

Statistically speaking the key is the use of ARD priors in the weights (for multi-view analysis) or in the factors (for multi-group analysis). You can find some more details in the supplementary information of the papers, also in [Chapter 3 and 5 of my PhD thesis](https://www.dropbox.com/s/4j7gasasvck206j/thesis.pdf?dl=0):

**Comment by statwangz** [comment]
> It can certainly be used for both multi-group and multi-view analysis. We have [a tutorial demonstrating multi-group analysis using scRNA-seq data](https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/scRNA_gastrulation.html). But you need some degree of overlap in the observations between groups and data modalities. MOFA doesn't work when one group of samples only has only modality 1 and the other group of samples has only modality 2.
> 
> Statistically speaking the key is the use of ARD priors in the weights (for multi-view analysis) or in the factors (for multi-group analysis). You can find some more details in the supplementary information of the papers, also in [Chapter 3 and 5 of my PhD thesis](https://www.dropbox.com/s/4j7gasasvck206j/thesis.pdf?dl=0):

Thank you for the quick reply!
