### ISSUE TITLE
Handling view of categorical data of which levels > 2

### ISSUE THREAD

**Issue by gmhhope** [bioFAM/MOFA2#126]
Hi MOFA2 developers,

Thanks for creating this amazing tool! I have a general question regarding some clinical data that might be categorical with levels > 2. How will the MOFA2 handle this type of data? 

Thanks,
Minghao Gong

**Comment by rargelaguet** [comment]
Hi Minghao,
unfortunately MOFA does not have any likelihood model that is able to capture categorical data. It's better if you train the model using the continuous data and subsequently perform an association analysis between the latent factors and the clinical variables.

Hope this is helpful and sorry for the late response
