### ISSUE TITLE
names(MOFAobject@expectations) keeps showing NULL

### ISSUE THREAD

**Issue by squirrelB** [bioFAM/MOFA2#136]
Hi. I'm on R version 4.1.1.
I've tried run_mofa() using my own data, and the CLL. 
It looks like it runs, and I get the "Converged!" And "Training Finished" messages.

But the expectations slot seems empty. (see attached screen shot). How do I resolve [this?]
<img width="1057" alt="Screenshot 2023-11-11 at 8 40 01 PM" src="https://github.com/bioFAM/MOFA2/assets/31778385/81b0b051-a0b6-40c0-a142-743bf05db95c">

**Comment by gtca** [comment]
Hey @squirrelB,

Could you show your `prepare_mofa()` and `run_mofa()` lines here as well?

**Comment by squirrelB** [comment]
Hi. Issue has been resolved! :)
I emailed Ricard and he responded, and advised that I have an outfile, which I had not.
So `run_mofa(MOFAobject, outfile=$file)`, and that made it work! 

Thank you so much for responding.
