### ISSUE TITLE
MOFA2 installation error

### ISSUE THREAD

**Issue by jpadesousa** [bioFAM/MOFA2#29]
Hello,

I would to try MOFA2 but I am having some issues installing it in RStudio using the following command:

`devtools::install_github("bioFAM/MOFA2/MOFA2", build_opts = c("--no-resave-data --no-build-vignettes"))`

I get the error message:

> Error : (converted from warning) unable to re-encode 'plot_data.R' lines 377, 378, 379
> ERROR: unable to collate and parse R files for package 'MOFA2'

It might be a problem from my side. I wasn't able to figure it out.
Also, I was able to install MOFA `devtools::install_github("bioFAM/MOFA", build_opts = c("--no-resave-data"))` without problems.

Thank you in advance,
Joao

> R.version
>                _                           
> platform       x86_64-w64-mingw32          
> arch           x86_64                      
> os             mingw32                     
> system         x86_64, mingw32             
> status                                     
> major          3                           
> minor          6.1                         
> year           2019                        
> month          07                          
> day            05                          
> svn rev        76782                       
> language       R                           
> version.string R version 3.6.1 (2019-07-05)
> nickname       Action of the Toes

**Comment by adoe21** [comment]
I'm having the same issue. From what I'm seeing it looks to be a Windows issue? Has anyone discovered a fix?

**Comment by gtca** [comment]
It appears to be related to Windows **and** to the encoding, e.g. [see this clarification from RStudio](https://support.rstudio.com/hc/en-us/articles/200532197-Character-Encoding).
You could check `Sys.getlocale()` output, try the same thing in R in the terminal, and/or check if changing the locale e.g. to `Sys.setlocale("LC_ALL", 'en_GB.UTF-8')` helps.

Please get back to us with updates to let us know if some of that maybe works!

The lines that the error message points to contain some Unicode characters. 
They are not important so you could also remove them from the source code of the cloned git repository and try installing the package.

**Comment by jpadesousa** [comment]
`Sys.getlocale()` returns:

> "LC_COLLATE=English_United Kingdom.1252;LC_CTYPE=English_United Kingdom.1252;LC_MONETARY=English_United Kingdom.1252;LC_NUMERIC=C;LC_TIME=English_United Kingdom.1252"

I tried using R in the terminal and changing the locale but the error continues.
Downloading the source code, editing those lines (by removing some strange added symbols to the string), and then installing it, solved the problem.

**Comment by gtca** [comment]
Thanks for trying all the options!

To increase compatibility with different setups I removed the lines of the code that were causing the problem (see https://github.com/bioFAM/MOFA2/commit/f52effc3f85becbd6f5332c527e03665883941bf and also https://github.com/bioFAM/MOFA2/commit/6b94fda2880bd1d0eba1a24befc9bf44408be09e).
Should work now!

**Comment by jpadesousa** [comment]
I just tried to install MOFA2 using:
`devtools::install_github("bioFAM/MOFA2/MOFA2", build_opts = c("--no-resave-data --no-build-vignettes"))`

I've got the following error:

> Error in findpack(package, lib.loc) : there is no package called 'MOFA2'
> Calls: <Anonymous> -> findpack
> Execution halted
> ERROR: lazy loading failed for package 'MOFA2'

Again, might be a problem from my part. Check if it installs smoothly in your machine. 
Cheers

**Comment by gtca** [comment]
Could it be a similar issue [to this one with permissions](https://community.rstudio.com/t/cant-install-package-remotes-when-trying-to-install-devtools/34121)?

The package installation seems to work:

```
> devtools::install_github("bioFAM/MOFA2/MOFA2", build_opts = c("--no-resave-data --no-build-vignettes"), force = TRUE)
Downloading GitHub repo bioFAM/MOFA2@master
from URL https://api.github.com/repos/bioFAM/MOFA2/zipball/master
Installing MOFA2
<...>
* installing *source* package 'MOFA2' ...
** R
** tests
** byte-compile and prepare package for lazy loading
<...>
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
<...>
* DONE (MOFA2)
```

**Comment by jpadesousa** [comment]
That's it! That was the problem.

Thank you so much for your help!
