### ISSUE TITLE
MultiAssayExperiment support dropped

### ISSUE THREAD

**Issue by frederikziebell** [bioFAM/MOFA2#31]
I'm trying to run MOFA2 and it seems there is no support for MultiAssayExperiment objects in `create_mofa()`. I think it's worth keeping MultiAssayExperiment support for several reasons:

- It enables users of MOFA1 to easily switch to MOFA2 with just a few lines of code
- It is easy to combine assays with different number of columns. Currently subsetting has to be done by the user if the list of matrices is used in the `data` slot.
- MultiAssayExperiment is actively developed and an elegant solution to store multi-table data
- Currently, there is no way to specify sample (column) annotation, which is very useful for downstream analyses

**Comment by rargelaguet** [comment]
I agree, we will add support.

Regarding the sample metadata, currently this has to be incorporated after the model has been loaded by doing: `samples_metadata(object) <- value`
where value is a data.frame which must at least contain the columns "sample" and "group". As in MOFA v1, you can also colour samples by external covariates in `plot_factors`.

We will try improve this, thanks for the feedback

**Comment by bv2** [comment]
We have added the MultiAssayExperiment support to MOFA2 (see CLL vignette). Thanks for the feedback and let us know if there are other functionalities that you are missing from MOFA1
