### ISSUE TITLE
Multi-omics not single cells

### ISSUE THREAD

**Issue by mhmism** [bioFAM/MOFA2#32]
Thanks for your recent interesting article.
I would like to use MOFA+ on my own multi-omics dataset. However my data is not single-cell based. 
Would MOFA+ be suitable to be applied on my own data? Or should I use the the previous MOFA version 1?

**Comment by rargelaguet** [comment]
MOFA+ remains 100% applicable to bulk data. I suggest everyone to update to MOFA+, even if not using the multi-group functionality (i.e. just setting one group, which is the default option). It is faster and has better functionalities for downstream analysis (including an interactive shiny R package https://github.com/gtca/mofaplus-shiny/)
