### ISSUE TITLE
error with run_mofa()

### ISSUE THREAD

**Issue by notimenocall** [bioFAM/MOFA2#33]
Hi,

Thanks for developing this nice package.
I ran into an error when using run_mofa() after finishing 4999 out of 5000 interation:
`Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: save() got an unexpected keyword argument 'expectations'`
Any idea what may have gone wrong? Thanks!!

Best,
Xiao

**Comment by gtca** [comment]
Hey,

Thanks for your feedback!
It looks like there's been a problem with concordance between R and Python API of a very recently added feature: there's been a new option introduced to save more information about the model (`expectations`) both to R and Python code.
It should be fixed now with https://github.com/bioFAM/MOFA2/commit/8bd9b0a8fdb0efdefdd91e45be717f20ac8b2082.

Please let us know if that fixes an issue for you.

**Comment by notimenocall** [comment]
Hey, Thanks a lot for your prompt response. It is working now!
