### ISSUE TITLE
NA for all variance explained

### ISSUE THREAD

**Issue by notimenocall** [bioFAM/MOFA2#35]
Hi MOFA2 team,
I was running MOFA2 and after 5000 iterations all the values returned such as variance_explained by factors are NaN. For example, if I plot_variance_explained() everything is grey. I ran MOFA2 with this data set (single cell RNA) before but not with the same set of genes and didn't have the problem. When I check MOFAmodel@training_stats, ELBO turns NaN after 446 iterations. Any idea what did I do wrong here?
Thank you very much!
Best,
Xiao

**Comment by rargelaguet** [comment]
Hi Xiao, 
are you using counts as input (modelled with Poisson likelihood) instead of normalised counts (modelled with Gaussian likelihood)?

**Comment by notimenocall** [comment]
I created mofa with an Seurat object using all the default setting. Before create_mofa, I suset the Seurat object to contain only the 1000 highly variable genes. The Seurat Object has ~33,000 cells.

**Comment by rargelaguet** [comment]
I need more details than this... could you send me the untrained MOFA object? Contact me via ricard@ebi.ac.uk or, better, using the MOFA Slack group: https://join.slack.com/t/mofahelp/shared_invite/enQtMjcxNzM3OTE3NjcxLWNhZmM1MDRlMTZjZWRmYWJjMGFmMDkzNDBmMDhjYmJmMzdlYzU4Y2EzYTI1OGExNzM2MmUwMzJkZmVjNDkxNGI

**Comment by gtca** [comment]
I will close this as of now. Please feel free to re-open this issue or to create a new one if there's a reproducible example for the problem.
