### ISSUE TITLE
Wrong convergence criteria documentation

### ISSUE THREAD

**Issue by frederikziebell** [bioFAM/MOFA2#38]
I trained a model with `convergence_mode = "slow"` and it converged at a relative deltaELBO of `0.00000050%`, which is 5e-7, but the documentation says 5e-6. I think the documentation is wrong for all three convergence modes by one order of magnitude.

Moreover, the documentation says `deltaELBO = ...`, but it's actually the percentage listed in brackets that is refered to.

I also think it is useful to print a message after model training in case the `maxiter` threshold is reached, especially when switching from medium to slow convergence

**Comment by gtca** [comment]
Hey @frederikziebell, thanks a lot for spotting that, I've updated the respective docstrings, it's now available in the `master` branch.
