### ISSUE TITLE
Error in scnmt_gastrulation.Rmd vignette

### ISSUE THREAD

**Issue by ibulanov** [bioFAM/MOFA2#42]
Hi there,

In the scNMT_gastrulation.Rmd vignette when I visualize the DNA methylation patterns for Factor 2, I have an error from `plot_data_heatmap` function (337-346 lines):
`Error in plot_data_heatmap(MOFAmodel, view = c("Enhancer methylation"), : There are rownames in annotation_samples that do not correspond to sample names in the model`

In the HTML version of vignette I saw `plot_data_heatmap` function parameter `annotation_col = df` instead of `annotation_samples`, but with `annotation_col` parameter I have:
`Error in pheatmap(data, annotation_row = annotation_features, annotation_col = annotation_samples,  : 
  formal argument "annotation_col" matched by multiple actual arguments`

Are you sure everything is correct? Could you please tell me what's wrong?

Thank you!

Best wishes,
Igor

**Comment by rargelaguet** [comment]
Hi Igor,
thanks for reporting this. The `annotation_samples` argument corresponds to an update that we recently made in the MOFA2 R package. If you update the package it should work!

Best,
Ricard.

**Comment by gtca** [comment]
I will close this thread assuming this has been fixed now and works for everyone but please feel free to re-open if you still encounter an error on your machine at this part of the vignette.
