### ISSUE TITLE
Wrong plot_variance_explained() units?

### ISSUE THREAD

**Issue by matrs** [bioFAM/MOFA2#47]
Hello, 
I've followed the official ["CLL" tutorial ](https://raw.githack.com/bioFAM/MOFA2/master/MOFA2/vignettes/CLL.html)  which I was able to replicate using the (already) trained model. I also trained the model locally using CPU and GPU and both worked without trouble ( I used the same parameters as the tutorial). The results look  similar to those from the tutorial  but the problem is that when I check the percentage of variance explained, It seems that I'm obtaining a small fraction of  it compared to that from the provided model, although the proportion between factors look similar to those from the vignette: 

![image](https://user-images.githubusercontent.com/12502882/86618822-8d47bb00-bf87-11ea-880c-d92241d2060b.png)

![image](https://user-images.githubusercontent.com/12502882/86619429-8a999580-bf88-11ea-8dd3-0a0a53657100.png)

These are the model and training options (same as the tutorial): 

```R
> model_opts
$likelihoods
      Drugs Methylation        mRNA   Mutations 
 "gaussian"  "gaussian"  "gaussian" "bernoulli" 

$num_factors
[1] 15

$spikeslab_factors
[1] FALSE

$spikeslab_weights
[1] TRUE

$ard_factors
[1] FALSE

$ard_weights
[1] TRUE
```

```R
> train_opts
$maxiter
[1] 1000

$convergence_mode
[1] "slow"

$drop_factor_threshold
[1] -1

$verbose
[1] FALSE

$startELBO
[1] 1

$freqELBO
[1] 1

$stochastic
[1] FALSE

$gpu_mode
[1] TRUE

$seed
[1] 42
```

```R
> MOFAobject
Trained MOFA with the following characteristics: 
 Number of views: 4 
 Views names: Drugs Methylation mRNA Mutations 
 Number of features (per view): 310 4248 5000 69 
 Number of groups: 1 
 Groups names: group1 
 Number of samples (per group): 200 
 Number of factors: 15 
```

I'm using `MOFA2 1.0` which I installed  following the instruction from this repo:

`remotes::install_github("bioFAM/MOFA2/MOFA2", build_opts = c("--no-resave-data --no-build-vignettes"))`

I'm in Linux and most of the dependencies were installed using `conda`.

Added:
I just checked the trans-kingdom tutorial and using the trained model from ftp://ftp.ebi.ac.uk I see this:

```R
plot_variance_explained(mofa, max_r2=1) # With bigger r2  nothing is displayed 
```

![image](https://user-images.githubusercontent.com/12502882/86627478-65ac1f00-bf96-11ea-8308-3aa5167e8d94.png)

**Comment by gtca** [comment]
Hello @matrs, thanks for creating this issue.

One thing, with the current `master` branch, explained variance (r2) should take values from 0 to 100. So using the latest Python `mofapy2` package and the latest R package `MOFA2` should bring your results closer to the vignettes.

Regarding the question about the CLL dataset, in the vignette, there is a `max_r2` parameter specified, which will make the variance explained plot to have more contrast. 
We generate vignettes automatically so it should be possible to get the exact same image considering we also set a certain seed. The only difference left I see is the `gpu_mode` but I wouldn't expect it to make (such) a difference. The question is does it look different with and without `gpu_mode` turned on then...

Please feel free to let us know in case that (still) or something else doesn't look right.

**Comment by matrs** [comment]
Hello, 
my results with CPU and GPU are the same. I'm using the last version of `mofa+` and `mofapy2`.  I'll repost  somethings,  maybe I wasn't clear. I produce all the plots  copying and pasting from the relevant vignettes:

```R
> package.version("MOFA2") 
[1] "1.1"
```
```bash
$ pip search mofapy2
mofapy2 (0.5.3)  - Multi-Omics Factor Analysis v2, a statistical framework for the integration of multi-group and multi-omics data
  INSTALLED: 0.5.3 (latest)

$ nvidia-smi 
Tue Jul 28 19:32:31 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.100      Driver Version: 440.100      CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
```

```R
train_opts
$maxiter
[1] 1000

$convergence_mode
[1] "slow"

$drop_factor_threshold
[1] -1

$verbose
[1] FALSE

$startELBO
[1] 1

$freqELBO
[1] 1

$stochastic
[1] FALSE

$gpu_mode
[1] FALSE

$seed
[1] 42

$maxiter
[1] 1000

$convergence_mode
[1] "slow"

$drop_factor_threshold
[1] -1

$verbose
[1] FALSE

$startELBO
[1] 1

$freqELBO
[1] 1

$stochastic
[1] FALSE

$gpu_mode
[1] FALSE

$seed
[1] 42
```
To use my GPU I do `train_opts$gpu_mode <- TRUE`, **the rest are the  same options.**

![GPU_CPU_stock](https://user-images.githubusercontent.com/12502882/88741171-f21cae00-d10c-11ea-8157-ba937d825b9f.png)



The last picture in my previous post is from the model **downloaded from the ebi ftp**, which has ,**coincidentally**, a variance explained  2 orders of magnitude  smaller than the displayed in the vignette, i didn't trained:

```{r}
mofa_trained <- readRDS(url("ftp://ftp.ebi.ac.uk/pub/databases/mofa/microbiome/model.rds"))
samples_metadata(mofa_trained) <- metadata
plot_variance_explained(mofa_trained, max_r2=1)
plot_variance_explained(mofa_trained, plot_total = T)[[2]]
```
![transk_stock](https://user-images.githubusercontent.com/12502882/88741188-fd6fd980-d10c-11ea-8769-9807b3affef0.png)


Also, I tried the `heterogeneous time-course single-cell RNA-seq dataset`, but only with my GPU:

```
#Relevant warning during training:
12 factors were found to explain no variance and they were removed for downstream analysis. You can disable this option by setting load_model(..., remove_inactive_factors = F)
```

![gpu_trained](https://user-images.githubusercontent.com/12502882/88741161-e8934600-d10c-11ea-9309-e7b998fc4e3f.png)

I hope somebody can run these analysis again, I don't think my training is the problem, specially seeing the trained model from the transkingdom vignette, which has indeed, as my trained models,  2 orders of magnitude difference with the ones from the vignette. 
I thought the plotting functions where the problem but I'm seeing the code where the R^2 get multiplied by 100 and also this, which  affirms the Rs are between one and two order of magnitude smaller: 

For the "CLL" data:
```R
#For the trained model download from the ftp:
r2_mk <- mofa_trained@cache$variance_explained$r2_per_factor
head(r2_mk)
$group1
                Drugs  Methylation        mRNA    Mutations
Factor1  1.365356e+01 17.348751009 7.125283490 2.239780e+01
Factor2  2.635139e+01  0.005045075 0.484325771 6.711440e-03
Factor3  3.253223e+00  0.518725190 4.830460203 5.722878e+00
Factor4  4.464539e-01  0.001590188 8.978938940 6.660298e-04
Factor5  4.935150e+00  0.002128087 2.883505501 9.371958e-04
Factor6  8.401008e-01  0.870148541 3.729148473 4.702484e-01
....
```
```R
#GPU trained model which has the same results as the CPU trained:
r2_gpu <- MOFAobject_gpu@cache$variance_explained$r2_per_factor
head(r2_gpu)
$group1
                Drugs  Methylation         mRNA    Mutations
Factor1  1.467324e-01 1.731314e-01 0.0705183718 2.253265e-01
Factor2  3.697858e-02 4.271090e-03 0.0458778737 4.966998e-02
Factor3  6.269341e-02 2.726844e-05 0.0285394242 1.326835e-05
Factor4  6.423798e-02 8.213537e-03 0.0060759614 8.930114e-05
Factor5  5.677782e-03 2.277119e-05 0.0601328747 9.858009e-06
Factor6  1.024029e-02 9.831171e-03 0.0386719952 3.920042e-04
....
```
So as a summary, I'm not able to reproduce any of the results showed in the paper/vignettes.

**Comment by rargelaguet** [comment]
Hi @matrs ,
Thanks for the feedback. Indeed it seems that the units are wrong and should be 100*x. In the 0.99.4 to 0.99.5 version upgrade we updated the R2 units from 0-1 to 0-100 in the `mofapy2` package, in [this commit](https://github.com/bioFAM/MOFA2/commit/7519f506533e7982bdd137d6e11862be877f6150#diff-64e1f00f2f41b13123c86ce081f9466b). From your pip search I see that you are using the `mofapy2` 0.5 version. Could you try update with `pip install mofapy2`?

Regarding GPUs, could you confirm that you get a significant speed up? We haven't had many users employing the GPU functionalities yet.

Best,
Ricard.

**Comment by matrs** [comment]
All the plots in my previous post were run yesterday with a fresh install of `mofa+` and `mofapy2`. I got the same results from almost one moth ago (when I started this issue), which was expected given no updates were pushed in this period of time. The weird thing is that I didn't have the code from the commit you pointed out when I checked my `mofapy2/build_model/save_model.py` :

```python
subgrp.create_dataset(self.groups_names[g], data=self.r2[g]*100
...
subgrp.create_dataset(self.groups_names[g], data=r2_total[g]*100
``` 

I did a  `pip install -U mofapy2 ` and I got the latest code, before I didn't use the upgrade option. Still I really don't understand why I didn't have that code because the first time I installed `mofapy2` was one month ago and that commit is from February. It should have been in `pipy` at that time so maybe something is wrong there:

```bash
#now my system has 0.5.4 although pip says the latest version is the one I had installed until yesterday
$ pip search mofapy2
mofapy2 (0.5.3)  - Multi-Omics Factor Analysis v2, a statistical framework for the integration of multi-group and multi-omics data
  INSTALLED: 0.5.4
  LATEST:    0.5.3
```

**Now the results have a similar variance.**  I haven't updated my MOFA-R version yet (since yesterday) but I think that code shouldn't  be involved  in my issue  and maybe isn't needed? I meant, as you say the Rs are being converted to percentages and my problem was the `mofapy2` version, that shouldn't be needed in the R code and maybe that update can create "false"  values in cases where the Rs are actually very small. I put a couple of print statements were that conversion is happening to confirm the multiplication, maybe you can write something there to let us know that Rs are being converted to percentages.

Regarding speed, with my GPU is almost 10 times faster:

```bash
#For CLL data GPU GTX 1070
user  system elapsed 
151.802   2.466 152.092 
```

```
#For CLL data CPU AMD Ryzen 5 3600 6-Core Processor, all cores used
user   system  elapsed 
1185.115 3711.996  467.865 
```
Thank you for your help

**Comment by rargelaguet** [comment]
Thanks again for your detailed response @matrs. The problem was that I forgot to update the mofapy2 version in PyPI, so everyone installing mofapy2 via pip had this issue. Should be fixed now. 
I guess that the difference between training with with 6 cores and a single GPU in a small data set (N=200) is not that significant. It should make a bigger difference with large data sets. Again, thanks for reporting this, it is very helpful. 

Let me know if I can close the issue.

**Comment by matrs** [comment]
Yep, i can close it too, thanks!
