### ISSUE TITLE
AttributeError: module 'mofapy2' has no attribute 'run.entry_point'

### ISSUE THREAD

**Issue by ClaireTeague** [bioFAM/MOFA2#48]
I am unable to 'run_mofa' despite previously this working fine.  This is the error I get:

Error in py_get_attr_impl(x, name, silent) :
  AttributeError: module 'mofapy2' has no attribute 'run.entry_point'

I am using R v3.6.1 in a virtual environment.

Thank you,
Claire

**Comment by mschubert** [comment]
Adding this information here as well for reference:


> Been running into this as well today, and I found the following helpful to debug (using MOFA2 and use_basilisk=FALSE):
>
> * Check `reticulate::py_config()` which python installation is used
> * Open this python in your terminal and try to import the module `from mofapy2.run import entry_point`
>
> The error message you get will be more helpful than what run_mofa displays

Also related, `run_mofa` with `use_basilisk=TRUE` seems to not install `mofapy2` in the pip environment [in some cases](https://github.com/bioFAM/MOFA/issues/50#issuecomment-698408015):

> I had the same issue running MOFA2 on RStudio Server. The error message said also: "AttributeError: module 'mofapy' has no attribute 'core.entry_point'" I noticed that r-reticulate generated a conda env by itself.
>
>So, I did not changed the conda_env for my MOFA run and installed mofapy2 by first accessing the r-reticulate env:
conda activate /home/XXX/.local/share/r-miniconda/envs/r-reticulate
>
> ```
>conda activate /home/XXX/.local/share/r-miniconda/envs/r-reticulate
>pip install mofapy2
>```
