### ISSUE TITLE
TypeError: set_train_options() got an unexpected keyword argument 'outfile'

### ISSUE THREAD

**Issue by cmzuo11** [bioFAM/MOFA2#49]
Dear authors,

When I run the function "run_mofa" in MOFA2 package, I got the following error:  "TypeError: set_train_options() got an unexpected keyword argument 'outfile'". 

Could you please help me to solve it?

Thanks,
Zuo

**Comment by rargelaguet** [comment]
Hi Zuo, thanks for reporting this. We've introduce a minor bug on the latest commit, could you please update both the mofapy2 python and the MOFA2 R packages?

**Comment by cmzuo11** [comment]
> Dear Richard,

Thanks for your quick reply, right now, I installed the mofapy2 and MOFA2 R package, It also has the same error.

best,
zuo

**Comment by gtca** [comment]
Hey Zuo,

I believe the problem might still be with mofapy2 Python version not being the updated one while using the latest MOFA2 R package version.

We've introduced an option to set model filename within training options (the `outfile` argument).
From the error message it looks like mofapy2 still doesn't know about that argument.
We've already updated the mofapy2 in PyPI with this functionality so upgrading to it should help:

```
pip install --upgrade --force-reinstall mofapy2
```

While updates to PyPI might be not aligned with our updates to the GitHub repository, you could also try updating the Python package using `master` branch on GitHub.

```
pip install git+https://github.com/bioFAM/MOFA2
```

**Comment by cmzuo11** [comment]
> Hey Zuo,
> 
> I believe the problem might still be with mofapy2 Python version not being the updated one while using the latest MOFA2 R package version.
> 
> We've introduced an option to set model filename within training options (the `outfile` argument).
> From the error message it looks like mofapy2 still doesn't know about that argument.
> We've already updated the mofapy2 in PyPI with this functionality so upgrading to it should help:
> 
> ```
> pip install --upgrade --force-reinstall mofapy2
> ```
> 
> While updates to PyPI might be not aligned with our updates to the GitHub repository, you could also try updating the Python package using `master` branch on GitHub.
> 
> ```
> pip install git+https://github.com/bioFAM/MOFA2
> ```

Yes, it works now. Thanks so much for your help.

Best,
zuo
