### ISSUE TITLE
variable %in% names(object@expectations) is not TRUE

### ISSUE THREAD

**Issue by snashraf** [bioFAM/MOFA2#50]
Hi team,

I was trying to run a simple script . Its just a copy from MOFA website.
```
rm(list = ls())
library(MOFA2)
library(MOFAdata)
library(data.table)
library(ggplot2)
library(tidyverse)
utils::data("CLL_data")  
file = "ftp://ftp.ebi.ac.uk/pub/databases/mofa/getting_started/data.txt.gz"
data = fread(file)
lapply(CLL_data,dim)
CLL_metadata <- fread("ftp://ftp.ebi.ac.uk/pub/databases/mofa/cll_vignette/sample_metadata.txt")
MOFAobject <- create_mofa(data)
data_opts <- get_default_data_options(MOFAobject)
model_opts <- get_default_model_options(MOFAobject)
model_opts$num_factors <- 10

train_opts <- get_default_training_options(MOFAobject)
train_opts$convergence_mode <- "slow"
train_opts$seed <- 42


MOFAobject <- prepare_mofa(MOFAobject,
                           data_options = data_opts,
                           model_options = model_opts,
                           training_options = train_opts
)

samples_metadata(MOFAobject) <- CLL_metadata
```

I am getting below error. 
> plot_factor_cor(MOFAobject)
Error in get_expectations(object, "Z", as.data.frame) : 
  variable %in% names(object@expectations) is not TRUE

My package version is 👍 > packageVersion("MOFA2")
[1] ‘1.1’
Could you please look in this issue and help me in debugging this error.

**Comment by gtca** [comment]
Hello @snashraf!

Thanks for reaching out.
I think the trick here is that adding metadata to the untrained model is something that is currently not supported.

In the vignette `MOFA2/vignettes/CLL.Rmd` (`MOFA2/vignettes/CLL.html`), the metadata is added to the trained model, i.e. in the call `samples_metadata(MOFAobject) <- CLL_metadata` the `MOFAobject` is a trained MOFA model.

And just to note, it is totally possible to carry metadata along with the model, and this works with objects that already contain metadata such as Seurat or MultiAssayExperiment. And when training from matrices or long data frames, it should be possible to add metadata after training. So training the model (`run_mofa`) before assigning `samples_metadata` in your example should resolve the issue.

**Comment by gtca** [comment]
Hey, I'm going to close it now.
Please feel free to re-open this issue if you have more questions about this topic.
