### ISSUE TITLE
MOFA+ doesn't work for R 3.6.1

### ISSUE THREAD

**Issue by GlastonburyC** [bioFAM/MOFA2#54]
Hi, MOFA+ used to work on my Docker build, but as of today, it fails, saying it only supports R 4.0. I cannot currently upgrade to R 4.0, what is the solution?

I am installing via:
`devtools::install_github("bioFAM/MOFA2", build_opts = c("--no-resave-data"))`

I get:
```
The downloaded binary packages are in
	/var/folders/bw/2h456p8x7v558z36s15958740000gn/T//RtmpTfTzNl/downloaded_packages
✔  checking for file ‘/private/var/folders/bw/2h456p8x7v558z36s15958740000gn/T/RtmpTfTzNl/remotes78da4cf41016/bioFAM-MOFA2-6d63e7c/DESCRIPTION’ ...
─  preparing ‘MOFA2’:
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘MOFA2_0.99.10.tar.gz’

ERROR: this R is version 3.6.1, package 'MOFA2' requires R >= 4.0
```

**Comment by rargelaguet** [comment]
Hi Craig, 
you need to clone the repository, edit the `Depends` entry of the DESCRIPTION file to:
`Depends: R (>= 3.0)`

Afterwards install with `R CMD INSTALL MOFA2`

**Comment by GlastonburyC** [comment]
Cheers, will do Ricard :)
