### ISSUE TITLE
mofa2 using all available cores

### ISSUE THREAD

**Issue by borauyar** [bioFAM/MOFA2#56]
Hi, 
A similar issue has been posted for MOFA before:
https://github.com/bioFAM/MOFA/issues/21

I can't find a way to control how many CPUs/Cores MOFA2 will use. It seems to make use of all available cores and really slows down the whole server and I end up just killing the mofa processes. It would be great if there was an easy way to just limit the number of cores used by MOFA2, ideally as an argument to the run_mofa function.

**Comment by rargelaguet** [comment]
Hi @borauyar ,
thanks for your feedback.  It clearly has to do with matrix operations that `mofapy2` does when training the model, but none of the developers have been able to reproduce this problem.. It seems to be specific to the numpy configuration in your server.

First, can you check wether you have MKL or BLAS libraries linked to numpy by running 
`python -c "import numpy; print(numpy.show_config())"`

If having MKL libraries linked to numpy you can specify the number of cores by defining this environmental variable:
`export MKL_NUM_THREADS=3`

If instead using BLAS libraries:
`export OMP_NUM_THREADS=1`

P.S. I learnt about this [here](http://www.diracprogram.org/doc/release-12/installation/mkl.html)

Please let me know if this works. If so, i'll add this on the troubleshooting section in our [webpage](https://biofam.github.io/MOFA2/).

**Comment by borauyar** [comment]
Hi @rargelaguet ,
Thank you very much. This definitely solved my problem! 
I have blas libraries linked and I can set the `OMP_NUM_THREADS`, which gives fine control over the number of threads used. 
Thank you!
