### ISSUE TITLE
error in get_expectations

### ISSUE THREAD

**Issue by elpavlos** [bioFAM/MOFA2#57]
Hi,

Thanks for the nice package!

I ran into an error trying to use plot_factor_cor(MOFAobject). 
Error in get_expectations(object, "Z", as.data.frame) : variable %in% names(object@expectations) is not TRUE.
When I applied names function on MOFAobject@expectations I got NULL. 
The MOFAobject was created with 2 sets (mRNA - 5000 genes and methylation - 5000 cg of 507 samples). 
In addition, I would like to know how many rows each of the different data sets should have. I tried without filtering (50,000 rows for each set) and got the following message:
Warning message:
In prepare_mofa(MOFAobject, data_options = data_opts, model_options = model_opts,  :
  Some view(s) have a lot of features, it is strongly recommended to perform feature selection before creating the MOFA object....

Thanks again!

**Comment by gtca** [comment]
Hey @elpavlos, thanks for reaching out.

Is `MOFAobject` a _trained_ MOFA object? The object itself should indicate its trained/untrained state:

```r
MOFAobject
## Untrained MOFA model with the following characteristics: 
##  Number of views: 4
##  ...
```

Expectations slots are set in the object after the training.

And the feature selection sounds reasonable in principle and is unlikely to be the cause of the error.

**Comment by elpavlos** [comment]
Hi, 
Thanks for the answer.
Indeed, it was an untrained object, it works now.
As for the feature selection, is there an optimum number of features per view to include in the object?

**Comment by gtca** [comment]
Great that it works now!

Feature selection would depend on the data, e.g. for count data such as gene expression or chromatin accessibility, one would typically select highly variable features (genes or peaks), usually it's a few thousand features out of dozens of thousands genes/peaks, and that's what's plugged into MOFA+. It is expected major results and insights would not depend on the fine details of feature selection, i.e. whether there were 4000 or 5000 genes selected.
