### ISSUE TITLE
How to create two views with this data (command)? How must be the data file to export to R?

### ISSUE THREAD

**Issue by geraldocantelli** [bioFAM/MOFA2#59]
Good afternoon,
I am using MOFA2 to analyze transcriptomic and metabolomic samples (with expression values).
I have a question: how must be the layout of the transcriptomic.csv and metabolomic.csv files in order to use read.table in R and create the dataframe input to MOFA2?
I can execute sucessfully with this:
     sample      feature     value
1        6h+P_R1  comparator0 0.8949565
2        6h-P_R1  comparator1 0.8949565
3        6h+P_R2  comparator2 0.7524568
4        6h-P_R2  comparator3 0.7524568
5       12h+P_R2  comparator4 1.0071812
6       12h-P_R2  comparator5 1.0071812
7       12h+P_R1  comparator6 0.9126984
8       12h-P_R1  comparator7 0.9126984
9       24h+P_R1  comparator8 1.1147821
10      24h-P_R1  comparator9 1.1147821
11      24h+P_R2 comparator10 1.3941942
12      24h-P_R2 comparator11 1.3941942
13      48h+P_R2 comparator12 0.1443008
14      48h-P_R2 comparator13 0.1443008
15      48h+P_R1 comparator14 0.7325429
16      48h-P_R1 comparator15 0.7325429
17      5C_6h_R1 comparator16 1.1993150
18      5P_6h_R1 comparator17 1.1993150
19      5C_6h_R2 comparator18 1.2373482
20      5P_6h_R2 comparator19 1.2373482
21   off_I5_rep1  comparator0 4.9353441
22   off_I5_rep2  comparator1 5.1068425
23   off_I5_rep3  comparator2 5.1840470
24   off_I5_rep4  comparator3 4.9202452
25  sp80_I5_rep1  comparator4 5.0577341
26  sp80_I5_rep2  comparator5 5.1254280
27  sp80_I5_rep3  comparator6 5.1201405
28  sp80_I5_rep4  comparator7 5.0262847
29 spont_I5_rep1  comparator8 5.2767589
30 spont_I5_rep2  comparator9 5.2716952
31 spont_I5_rep3 comparator10 5.1701737
32 spont_I5_rep4 comparator11 5.2201852
33   off_I5_rep1 comparator12 4.9353441
34   off_I5_rep2 comparator13 5.1068425
35   off_I5_rep3 comparator14 5.1840470
36  sp80_I5_rep1 comparator15 5.0577341
37  sp80_I5_rep2 comparator16 5.1254280
38  sp80_I5_rep3 comparator17 5.1201405
39 spont_I5_rep1 comparator18 5.2767589
40 spont_I5_rep3 comparator19 5.1701737

But it creates an MOFAobject with just one view. I tried many different ways to configure two views but without sucess. Could you help me please?
Best regards,
Geraldo
Bioinformatic Specialist

**Comment by rargelaguet** [comment]
Hi Geraldo,
you have to concatenate both data.frames row-wise and have a column called "view" that indicates whether the feature belongs to rna or metabolomics

**Comment by geraldocantelli** [comment]
Thank you very much.
Now it runs!
Congratulations for your excellent software.

**Comment by geraldocantelli** [comment]
Good morning. 
Could you help one more time please?
When the process finishes, it create the model file, but I cannot load it: (this error occurs:)
Error in if (max(sapply(object@cache$variance_explained$r2_total, max)) <  : 
absent value where TRUE/FALSE is needed

**Comment by rargelaguet** [comment]
That is strange. Could you (1) attach the command line output here and (2) send me the .hdf5 object by email (ricard.argelaguet@gmail.com)

**Comment by geraldocantelli** [comment]
My Rscript content is:

library(data.table)
library(MOFA2)
library(reticulate)
library(dplyr)

# Using a specific python binary
use_python("/home/geraldo/.local/share/r-miniconda/envs/r-reticulate/bin/python")

transcriptome <- read.table ("/home/geraldo/eclipse-workspace/wsapp/WebContent/apprMOFA/transcriptome.csv", sep = "\t",
							 header = TRUE, stringsAsFactors=F)

metabolome <- read.table ("/home/geraldo/eclipse-workspace/wsapp/WebContent/apprMOFA/metabolome.csv", sep = "\t",
							 header = TRUE, stringsAsFactors=F)

dt <- rbind(rowwise(transcriptome),rowwise(metabolome))

MOFAobject <- create_mofa(dt)

print(MOFAobject)

data_opts <- get_default_data_options(MOFAobject)

model_opts <- get_default_model_options(MOFAobject)

model_opts$num_factors <- 7

train_opts <- get_default_training_options(MOFAobject)

MOFAobject <- prepare_mofa(
  object = MOFAobject,
  data_options = data_opts,
  model_options = model_opts,
  training_options = train_opts
)

outfile = file.path(getwd(),"model.hdf5")

MOFAobject.trained <- run_mofa(MOFAobject, use_basilisk = FALSE, outfile)

Thank you in advance, I will send the request file through email.

**Comment by geraldocantelli** [comment]
I was able to fix the code and now it runs. Thank you.
