### ISSUE TITLE
Error with run_mofa()

### ISSUE THREAD

**Issue by ichcha-m** [bioFAM/MOFA2#61]
Hello,

I am running the tutorial: 'MEFISTO with temporal data' and have encountered an error.
AttributeError: 'entry_point' object has no attribute 'set_mefisto_options'.

I have mofapy2 V6.0 installed and v1.1.9 of MOFA2 in R. When I first started running the tutorial I got this error - Error in get_default_smooth_options(sm) : could not find function "get_default_smooth_options".
I noticed that there was a recent update to the R package where smooth was renamed to mefisto and so I used -

```
smooth_opts <- get_default_mefisto_options(sm)

sm <- prepare_mofa(sm, model_options = model_opts,
                   mefisto_options = smooth_opts,
                   training_options = train_opts)
```

After this, when I run -  
```
sm <- run_mofa(sm)
```
I get this error -  AttributeError: 'entry_point' object has no attribute 'set_mefisto_options'.

I looked at the entry_point.py file in mofapy2 and noticed that the set_smooth_options has not been renamed to set_mefisto_options. Could this be a reason for this error?

Please let me know if there is another version of MOFA2 in R or python I could install to make the tutorial run. Thanks in advance.

Ichcha

**Comment by bv2** [comment]
Hi, thanks for reporting this bug, which was indeed due to the recent renaming of the options.  Please update to the latest version of the R package MOFA2 (v1.1.10), where the problem should be fixed. We will also update the vignettes, which still have the old names on it.

**Comment by emdann** [comment]
Hi, 
Just reporting that I encounter the same error when using `run_mofa` and not when running `run_mefisto`, using v1.1.20 (`mofapy2` v0.6.2).

My object:
```
> myeloid_mofa
Untrained MOFA model with the following characteristics: 
 Number of views: 9 
 Views names: BM GU KI LI MLN SK SP TH YS 
 Number of features (per view): 6857 6857 6857 6857 6857 6857 6857 6857 6857 
 Number of groups: 19 
 Groups names: Basophil CD14_monocyte CLP DC_progen DC1 DC2 DC3 Eosinophil_MOP ERY_MAC GMP HSC_MPP MAC MAST_cell Mono_Mac MPP_MYE myelocyte neutrophil promonocyte Promyelocyte 
 Number of samples (per group): 20 25 21 11 22 29 24 19 23 17 19 22 20 25 18 8 21 23 19
```

Running MOFA:
```
data_opts <- get_default_data_options(myeloid_mofa)
data_opts$center_groups <- FALSE

model_opts <- get_default_model_options(myeloid_mofa)
model_opts$num_factors <- 10

train_opts <- get_default_training_options(myeloid_mofa)
train_opts$seed <- 2020
train_opts$convergence_mode <- "fast" # use "fast" for faster training
train_opts$stochastic <- TRUE

myeloid_mofa <- prepare_mofa(
  object = myeloid_mofa,
  data_options = data_opts,
  model_options = model_opts,
  training_options = train_opts
) 

myeloid_mofa_trained <- run_mofa(myeloid_mofa, outfile = outfile)
```
I get error:
```
Error in py_call_impl(callable, dots$args, dots$keywords) : AttributeError: 'entry_point' object has no attribute 'smooth_opts'
```

Running MEFISTO:
```
myeloid_mofa <- set_covariates(myeloid_mofa, covariates = "time")

data_opts <- get_default_data_options(myeloid_mofa)

model_opts <- get_default_model_options(myeloid_mofa)
model_opts$num_factors <- 10

train_opts <- get_default_training_options(myeloid_mofa)
train_opts$seed <- 2020
train_opts$convergence_mode <- "fast" # use "fast" for faster training

mefisto_opts <- get_default_mefisto_options(myeloid_mofa)
mefisto_opts$warping <- FALSE
# mefisto_opts$sparseGP <- TRUE

myeloid_mofa <- prepare_mofa(
  object = myeloid_mofa,
  data_options = data_opts,
  model_options = model_opts,
  training_options = train_opts,
  mefisto_options = mefisto_opts
) 
```
I get no issue.

Any suggestions?

**Comment by gtca** [comment]
I guess we can reopen it then.

I am not sure how to resolve it so far though, it looks fine [for the latest Docker image](https://hub.docker.com/repository/docker/gtca/mofa2/general) with the versions you mentioned.

**Comment by emdann** [comment]
Update: setting `train_opts$stochastic <- FALSE` solves it.
Hope this helps.

**Comment by gtca** [comment]
This is a bug to be fixed then, thanks for reporting!

**Comment by bv2** [comment]
Hi @emdann ,
thanks for reporting this and pinpointing it to the stochastic option.
The bug should be fixed now with the new version `MOFA2_1.1.21` and `mofapy2_0.6.3`.
Let us if you still encounter this issue with the new version.
