### ISSUE TITLE
Problem with time series and set_covariates

### ISSUE THREAD

**Issue by superlsd** [bioFAM/MOFA2#62]
Hi,
I am new to GitHub, so I don't well how it should be the procedure.
I have tried to use MOFA2 for time-dependent datasets to use MEFISTO (https://biofam.github.io/MOFA2/MEFISTO.html), 
but there were problems with the integration of the time covariate.
Using a dataframe that has also a time variable would result in the following error:
Error in create_mofa_from_df(evodevo) : 
  all(colnames(df) %in% (c("sample", "feature", "value", "group",  .... is not TRUE

While if I try to ignore the time component and then add it afterward as covariate I will obtain this other error:
Error in set_covariates(sm, covariates = ecodevo$time) : 
  could not find function "set_covariates"

I think there is a problem with set_covariates that is not defined with the normal installation of MOFA2 and it was solved only by cloning from the GitHub page.

**Comment by gtca** [comment]
Hi @superlsd, thanks for your feedback!

We have recently updated MOFA2 R package to `1.1.12` (`master` branch of this repo) and [mofapy2 Python library](https://pypi.org/project/mofapy2/) to `0.6.1`. 
If this fixes all your issues, that's great, downstream repositories like [bioc devel](https://bioconductor.org/packages/devel/bioc/html/MOFA2.html) will be updated soon, I guess.

**Comment by bv2** [comment]
Hi, 

MEFISTO is only available for MOFA2 (>=1.1.4). The latest version of MOFA (1.1.12) can be installed via 

devtools::install_github("bioFAM/MOFA2", build_opts = c("--no-resave-data --no-build-vignettes")) 

or from Bioconductor devel version:

BiocManager::install(version='devel')
BiocManager::install("MOFA2")

Let us know if the errors you mentioned still persist with the newest MOFA2 version.

**Comment by superlsd** [comment]
Thank you! With the developmental installation works :)
