### ISSUE TITLE
Fast convergence of the model & highly correlated factors!

### ISSUE THREAD

**Issue by asifemon** [bioFAM/MOFA2#63]
Hi Folks,

I am using MOFA2 for integrating proteomics targetted, untargeted, and metabolomics datasets with a sample size of approx 500 to 800 depending on different combinations. I have normalized the datasets with quantile normalization before training. However, I am having few issues while training the model.

1. The model is converging very fast (within 3-4 iterations) even after using convergence mode to slow.
2. Even if I am using only 5 factors for training the model producing highly correlated factors.

As a consequence, the model can not produce any meaningful outcome (in terms of biological interpretations) so far. Any suggestions are highly appreciated. In case this is not the right place for such discussion, could you please direct me to any support forum?

[warning_messages.txt](https://github.com/bioFAM/MOFA2/files/5982133/warning_messages.txt)

**Comment by rargelaguet** [comment]
Hi Asif,
that’s weird. Can you send me the training output? Also, if possible, it would be useful if you could send me privately the MOFA object before the run_mofa command. Via the mofa slack group (https://biofam.github.io/MOFA2/contact.html) would be easier

Best,
Ricard

**Comment by asifemon** [comment]
solved!
