### ISSUE TITLE
Error in py_call_impl: High bound not valid 

### ISSUE THREAD

**Issue by andrewjkwok** [bioFAM/MOFA2#67]
Hi,

I'm trying to run MOFA2 on 2 data matrices, and the process goes smoothly until the very end, when an error comes up after convergence and training finishing - the error is:

```
Iteration 573: time=0.39, ELBO=-958334.76, deltaELBO=0.404 (0.00000497%), Factors=10

Converged!



#######################
## Training finished ##
#######################


Saving model in /well/combat/users/ifl143/projects/bulk_MOFA/output/cytofprop_bulkgex_model.hdf5...
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: High bound is not valid (high bound is not valid)
```

On traceback, this is what I get:
```

11. stop(structure(list(message = "ValueError: High bound is not valid (high bound is not valid)", call = py_call_impl(callable, dots$args, dots$keywords), cppstack = structure(list(file = "", line = -1L, stack = c("/gpfs3/well/combat/users/ifl143/R/4.0/ivybridge/reticulate/libs/reticulate.so(Rcpp::exception::exception(char const*, bool)+0x69) [0x2ae6efb48e49]", "/gpfs3/well/combat/users/ifl143/R/4.0/ivybridge/reticulate/libs/reticulate.so(Rcpp::stop(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x25) [0x2ae6efb38e26]", ...
10. h5py at h5p.pyx#1206
9. h5py at _objects.pyx#55
8. h5py at _objects.pyx#54
7. make_fapl at files.py#120
6. __init__ at files.py#441
5. __init__ at save_model.py#47
4. save at entry_point.py#1188
3. mofa_entrypoint$save(outfile, save_data = save_data)
2. .run_mofa_reticulate(object, outfile, save_data)
1. run_mofa(MOFAobject, outfile)


```

Despite extensive searching I cannot seem to find related errors reported for MOFA2 and I'm not sure whether this is MOAF2 specific or related to some of the underlying python libraries. 

Please let me know what else could help solve the issue. Many thanks in advance!

**Comment by andrewjkwok** [comment]
A bit more information:

When running the analysis as a job rather than interactively, the traceback looks like this:

```
Saving model in /well/combat/users/ifl143/projects/bulk_MOFA/output/cytofprop_bulkgex_model.hdf5...
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: High bound is not valid (high bound is not valid)

Detailed traceback: 
  File "/gpfs3/well/combat/users/ifl143/python/mofa_gcc9.3.0_skylake/lib/python3.8/site-packages/mofapy2/run/entry_point.py", line 1188, in save
    tmp = saveModel(
  File "/gpfs3/well/combat/users/ifl143/python/mofa_gcc9.3.0_skylake/lib/python3.8/site-packages/mofapy2/build_model/save_model.py", line 47, in __init__
    self.hdf5 = h5py.File(outfile,'w')
  File "/gpfs3/well/combat/users/ifl143/python/mofa_gcc9.3.0_skylake/lib/python3.8/site-packages/h5py/_hl/files.py", line 441, in __init__
    fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds)
  File "/gpfs3/well/combat/users/ifl143/python/mofa_gcc9.3.0_skylake/lib/python3.8/site-packages/h5py/_hl/files.py", line 120, in make_fapl
    plist.set_libver_bounds(low, high)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  Fil
Calls: run_mofa ... .run_mofa_reticulate -> <Anonymous> -> py_call_impl
```

Looking into h5py, I'm wondering if there is an issue with version bounding? (https://buildmedia.readthedocs.org/media/pdf/h5py/latest/h5py.pdf (page 17 / 21) 4.1.4 Version bounding).

The HDF5 module that is loaded on my cluster when I've been running MOFA is:
`HDF5/1.10.6-gompi-2020a
`

Does this provide any more clues as to how I may fix this issue? Thank you.

**Comment by gtca** [comment]
Hey @andrewjkwok, thank you for reaching out!

I don't think we've seen such error before, and it looks like an HDF5/h5py issue indeed. Does [the simple example](https://docs.h5py.org/en/stable/quick.html#appendix-creating-a-file) work for you?

```python
import h5py
with h5py.File("mytestfile.hdf5", "w") as f:
    dset = f.create_dataset("mydataset", (100,), dtype='i')
```

Would trying other versions help such as newer ones, such as `HDF5/1.10.7-gompi-2020b` for instance? (Not sure you have a newer module available.)

**Comment by gtca** [comment]
Oh, if you want to run it from R, you can also do it:

```R
library(reticulate)
h5py <- import("h5py")
f = h5py$File("mytestfile.hdf5", "w")
dset <- f$create_dataset("mydataset2", 100L, dtype="i")
f$close()
```

**Comment by andrewjkwok** [comment]
Thanks for the suggestions. Unfortunately I don't have any other newer HDF5 versions to load - plus (forgive my ignorance if incorrect!) I think all of my modules need to be aligned for things to work and as I'm using an R module that's 2020a, I think I have to stick to what I currently have for 1.10.6?

When trying the simple example in R - I fail at 
`f <- h5py$File("mytestfile.hdf5", "w")`
with the same error of
`Error in py_call_impl(callable, dots$args, dots$keywords) : ValueError: High bound is not valid (high bound is not valid)`

So it definitely seems to be a compatibility issue between my hdf5 and h5py. Is there a specific version of hdf5 that is compatible with the software that I need to perhaps ask my cluster maintenance team to install for me?

**Comment by andrewjkwok** [comment]
When I test

```
import h5py
with h5py.File("mytestfile.hdf5", "w") as f:
    dset = f.create_dataset("mydataset", (100,), dtype='i')
```

Surprisingly this works ok, which suggests that there's something going on with the reticulate link between R and python? As I am running this on a cluster, the interactive nodes do not have internet access i.e. using basilisk is not an option. I checked my python configuration with `reticulate::py_config()`, I get:

```
python:         /gpfs3/well/combat/users/ifl143/python/mofa_gcc9.3.0_ivybridge/bin/python3
libpython:      /apps/eb/dev/ivybridge/software/Python/3.8.2-GCCcore-9.3.0/lib/libpython3.8.so
pythonhome:     /gpfs3/well/combat/users/ifl143/python/mofa_gcc9.3.0_ivybridge:/gpfs3/well/combat/users/ifl143/python/mofa_gcc9.3.0_ivybridge
version:        3.8.2 (default, May 30 2020, 13:15:28)  [GCC 9.3.0]
numpy:          /gpfs3/well/combat/users/ifl143/python/mofa_gcc9.3.0_ivybridge/lib/python3.8/site-packages/numpy
numpy_version:  1.20.2

NOTE: Python version was forced by use_python function
```

This was after I'd put run `reticulate::use_python("/well/combat/users/ifl143/python/mofa_gcc9.3.0_ivybridge/bin/python3", required=TRUE)` as the first line of code in my script. I notice that the libpython path is not pointing to where I would like the libraries to come from for my pyenv i.e. `/gpfs3/well/combat/users/ifl143/python/mofa_gcc9.3.0_ivybridge/`. Is this the potential issue?

**Comment by gtca** [comment]
I don't think there are any recent version of HDF5 that MOFA2/mofapy2 is not compatible with but we also didn't test it extensively. I just checked that [our docker image](https://hub.docker.com/r/gtca/mofa2) uses `1.12` for instance:

```python
>>> h5py.version.hdf5_version
'1.12.0'
>>> h5py.version.version
'3.2.1'
```
From the latest warning  you shared, it seems like this is exactly the issue, and you either have to load the corresponding module (`HDF5/1.12.0-gompi-2020a`?) or to create an environment (e.g. conda) to then install the build the user version of h5py against the correct HDF5 version.

But I would expect that using `use_python()` with the correct Python path should lead to the same result as the Python code. Can't really say what happens there. Is exactly the same path used that you see when running `which python` or `which python3`?

**Comment by andrewjkwok** [comment]
Hello - I've managed to fix things by getting the HDF5 module to be the same version as the HDF5 version for H5py. Thank you for the help!
