### ISSUE TITLE
Input Scenic regulons into multimodal embedding

### ISSUE THREAD

**Issue by kristiangu** [bioFAM/MOFA2#68]
Hi,

Thanks for the fantastic tool. I was wondering if it would be possible to input Scenic regulons (AUCell) as view in the mofa model, and if you ever tried to do so. Also, would this also require correction via limma etc. similarly to the RNA counts?

Thanks.

**Comment by rargelaguet** [comment]
This is an excellent question! 
I am indeed trying this for the analysis of single-cell multi-omics data (https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/10x_scRNA_scATAC.html).

As long as the regulations are continuously distributed (ideally normal-ish) you are fine. If you want, feel free to share the following plots via Slack channel (link here https://biofam.github.io/MOFA2/contact.html) and I'll be able to provide better guidance:
- histogram of the regulon data, before fitting the model
- variance decomposition analysis, after fitting the model
