### ISSUE TITLE
Problems with NA values

### ISSUE THREAD

**Issue by geraldocantelli** [bioFAM/MOFA2#73]
Hello, I have an input file with NA values that are read by read.table (..).
I already tested the values with is.na(allData$value) and it's really NA.
But when I try to run MOFA2, it appears the message:
Error in vapply(indices, fun, .default) : values must be type 'logical',
 but FUN(X[[1]]) result is type 'integer'
Calls: create_mofa ... as.matrix -> <Anonymous> -> cast -> vaggregate -> vapply
Execution halted
Could some one help me please?

**Comment by gtca** [comment]
Hey @geraldocantelli, we'd need a reproducible example in order to help, this is not something that I have encountered myself.

**Comment by geraldocantelli** [comment]
My coordinator had given an SQL code for me to concatenate the name of the features with a couple of internal gene symbols of our laboratory.
When I cut off this part of code, everything run sucessfully.
Thank you for the attention.
Best regards,
Geraldo
