### ISSUE TITLE
problem with mofa2 training

### ISSUE THREAD

**Issue by gittina** [bioFAM/MOFA2#76]
Hi, 
I installed MOFA2 (1.2.0) from Bioconductor. My R version is 4.1.  I was going through your tutorial "MOFA2: training a model in R", when the execution halted with the following message:

```
Connecting to the mofapy2 package using basilisk. 
    Set 'use_basilisk' to FALSE if you prefer to manually set the python binary using 'reticulate'.
Error in py_get_attr_impl(x, name, silent) : 
  AttributeError: module 'mofapy2' has no attribute 'run.entry_point'
```

As far as I understood, the default option for use_basilisk is FALSE, so I set it to TRUE to install the necessary dependencies automatically, and then I got the message above. 

Thank you in advance!
Martina

**Comment by gtca** [comment]
Hi Martina,

Does this error still occur if you restart the R session and use `use_basilisk = TRUE` at the first instance of calling `run_mofa()`?

Having quickly tried it with `use_basilisk = TRUE` with the latest MOFA2 1.3.4 from this repository, I couldn't reproduce the issue so far.

**Comment by gittina** [comment]
Yes, it occurs also after the restart.

Here's the code I wrote based on the tutorial:
```

library(data.table)
library(MOFA2)

data <- make_example_data(n_views = 2,
                          n_samples = 200, 
                          n_features = 1000, 
                          n_factors = 10)

m_data <- create_mofa(data$data)

plot_data_overview(m_data)

data_opts <- get_default_data_options(m_data)
model_opts <- get_default_model_options(m_data)
train_opts <- get_default_training_options(m_data)

MOFAobject <- prepare_mofa(object = m_data,
                           data_options = data_opts,
                           model_options = model_opts,
                           training_options = train_opts)

outfile = file.path(getwd(),"model.hdf5")

MOFAobject.trained <- run_mofa(MOFAobject, outfile, use_basilisk = TRUE)
```

**Comment by gtca** [comment]
The error message in the original message does look as if `mofapy2` is somehow not properly configured by basilisk.
It might be helpful to inspect that further with 

```r
library(basilisk)
# useBasiliskEnv(...) if needed
listPackages()
```

to see what packages basilisk have installed.
Basilisk environments should also be visible via `conda env list`.

@rargelaguet might have more experience with basilisk?..

Alternatively, a conda environment with `mofapy2` can be managed without basilisk of course, but that's a few more steps (create an environment with `conda create` and use the respective Python installation with `reticulate::use_python`).

**Comment by gittina** [comment]
Ok, so I tried with the command proposed above and this is the output:

```
  full                package
1              certifi==2020.4.5.1                certifi
2                     cffi==1.14.0                   cffi
3                   chardet==3.0.4                chardet
4                     conda==4.8.3                  conda
5    conda-package-handling==1.7.0 conda-package-handling
6              cryptography==2.9.2           cryptography
7                        idna==2.9                   idna
8                      pip==20.0.2                    pip
9                   pycosat==0.6.3                pycosat
10                 pycparser==2.20              pycparser
11               pyOpenSSL==19.1.0              pyOpenSSL
12                  PySocks==1.7.1                PySocks
13                requests==2.23.0               requests
14            ruamel-yaml==0.15.87            ruamel-yaml
15 setuptools==46.4.0.post20200518             setuptools
16                     six==1.14.0                    six
17                    tqdm==4.46.0                   tqdm
18                 urllib3==1.25.8                urllib3
19                   wheel==0.34.2                  wheel
```

Should mofapy2 be enlisted here?
Sorry, but honestly I'm not understanding how the connection between R and Python should be set. I read about it in the doc but I thought that the configuration of basilisk should have been done only when  manually installing Mofa+.

Thanks again!

**Comment by gtca** [comment]
Hey, apparently one has to also specify a correct MOFA environment for this. E.g. with `conda env list`, there should be one with a path like `.../basilisk/1.4.0/MOFA2/1.3.4/mofa_env`. This can then be used as an argument to `listPackages()`:

```r
> listPackages(".../basilisk/1.4.0/MOFA2/1.3.4/mofa_env")
                              full         package
...
6                   mofapy2==0.6.4         mofapy2
...
```

That being said, still not sure where it breaks with `basilisk`. Configuration-wise, for `use_basilisk = TRUE`, no tinkering should be required, and `basilisk` would create a new (or re-use an existing) environment with `mofapy2`.

Maybe it's worth trying to remove the environment so that `basilisk` creates a fresh one:

```bash
# in your terminal:
conda env remove -p ".../basilisk/1.4.0/MOFA2/1.3.4/mofa_env"

# and then run_mofa(..., use_basilisk = TRUE) in R
```

---

An alternative approach would be to handle `mofapy2` installation manually. This doesn't necessarily need to be a conda environement, just any Python installation with `mofapy2`. In this case the right Python installation (in case there are multiple ones on the machine) can be pointed to explicitly:

```r
> library(reticulate)
> use_python("/usr/bin/python")  # this can be Python from a conda env
```

**Comment by gittina** [comment]
Ok, so apparently I managed to install mofapy2 under python3 now. So at least from the python3 shell I'm now able to follow some steps of the python notebook proposed on your website. 

This work with Python 3.6:
`from mofapy2.run.entry_point import entry_point`

However, I'm still in trouble with R. 

I specified the python installation:
```
library(reticulate)
use_python("/usr/bin/python3") 
```
and then run:

`MOFAobject.trained <- run_mofa(MOFAobject, outfile, use_basilisk = FALSE)`

But I'm still getting the very same error.
Am I doing something wrong?

**Comment by gittina** [comment]
Hey, I restarted the system, not only the session and this apparently solved the problem, since this morning it completed the training without issues!

So, thanks for your time and help!
Martina

**Comment by jwchiles** [comment]
I know this one is closed but I did want to contribute my experience as well.  My lab was trying to get this running on our cluster and kept running into that error message from above.  The way we seem to have gotten around this was creating a conda environment with mofapy2 and python installed, then using basilisk to point to that environment like so:

`library(basilisk)
useBasiliskEnv("/usr/bin/.conda/envs/mofa_env")`

And then by calling run_mofa without basilisk:

`MOFAobject.trained <- run_mofa(MOFAobject, outfile, use_basilisk = FALSE)`

Not sure if this helps the devs or anyone else but thought I would put it out there just in case.

**Comment by mschubert** [comment]
I had this issue as well with a clean `basilisk=TRUE` environment. Apparently, the `mofapy2` package was not automatically installed when setting up the environment.

I think this is a bug and hence the issue should be reponened. At least me, @jwchiles and @jonasboh seem to be affected.
