### ISSUE TITLE
plot_data_overview and loading model from hdf5 always indicate wrong number of features per view and number of samples per group

### ISSUE THREAD

**Issue by marangiop** [bioFAM/MOFA2#78]
I train my model on n=134 sample, with two views encoded as two matrices within a list. Only 1 group. Selected to train on 10 factors.

```
Successfully loaded view='view_1' group='group1' with N=134 samples and D=18598 features...
Successfully loaded view='view_2' group='group1' with N=134 samples and D=1762 features...
```

MOFAobject (before and after training) looks as follows
```
> MOFAobject
Untrained MOFA model with the following characteristics:
 Number of views: 2
 Views names: view_1 view_2
 Number of features (per view): 18598 1762
 Number of groups: 1
 Groups names: group1
 Number of samples (per group): 134
```

After loading the mode at the end of training for doing downstream analysisl, the model information looks wrong. in particular, number of features (per view) and number of samples (per group) are both wrong.

```
> filepath <- system.file("extdata", "model.hdf5", package = "MOFA2")
> model <- load_model(filepath)
> model
Trained MOFA with the following characteristics:
 Number of views: 2
 Views names: view_0 view_1
 Number of features (per view): 1000 1000
 Number of groups: 1
 Groups names: single_group
 Number of samples (per group): 100
 Number of factors: 10

```
Consistent with this, the plot generated by plot_data_overview(model) also makes no sense.

![image](https://user-images.githubusercontent.com/29339953/134436472-326f0fa7-5ba0-45d7-9830-559fdd437375.png)

Any idea of what is going wrong here?

**Comment by gtca** [comment]
Hey, the number of features and samples does seem correct, it's just that the file `filepath` in your example is not the model trained by the user but rather something that comes with the MOFA2 package:

```{r}
filepath <- system.file("extdata", "model.hdf5", package = "MOFA2")
filepath
# => .../Resources/library/MOFA2/extdata/model.hdf5
```
