### ISSUE TITLE
Mofapy2 v0.6.4 won't run in R

### ISSUE THREAD

**Issue by hleegwater** [bioFAM/MOFA2#79]
Hi! I was following your tutorial on https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/getting_started_R.html and it looks really nice. I have a small note and a problem with versions of my python and your R code.

- I noticed that you wrote that a template script could be found somewhere, but the link refers to https://github.com/bioFAM/MOFA2/blob/master/template_script.R and that file no longer exists. If you have time, you could maybe change that to a working link?
- 
- within run_mofa() your code states:
`if (mofa$version$`__version__` != "0.6.3") {
warning(sprintf("The latest mofapy2 version is 0.6.3, you are using %s. Please upgrade with 'pip install mofapy2'", 
mofa$version$`__version__`))
have_mofa2 <- FALSE`
However, I now have mofa2py version 0.6.4 so I also get the error and the code will no longer work. 

I'll try to make a conda env with version 0.6.3 and see if that fixes my problem. 

Update: making a conda env with version 0.6.3 fixed the problem. Now I can analyze the tutorial data! :D

**Comment by rargelaguet** [comment]
Thansk for reporting Hanneke, this is now fixed in 474ff3af748f380d64690b2cdb52f3d7ed48d19e. You can reinstall the latest R package manually using: 
`devtools::install_github("bioFAM/MOFA2", build_opts = c("--no-resave-data --no-build-vignettes"))`

**Comment by rargelaguet** [comment]
P.S. Here is the `template_script.R`: 
```https://github.com/bioFAM/MOFA2/blob/master/inst/scripts/template_script.R```
