### ISSUE TITLE
Question regarding correlate_factors_with_covariates

### ISSUE THREAD

**Issue by FloraMika** [bioFAM/MOFA2#80]
Dear Sir or Madam,

Thank you very much for this amazing tool.

I just have a question regarding the correlate_factors_with_covariates function. In the function description it is indicating that numerical values and pearson correlation are used. How can it deal with "Gender" and "died" in the following tutorial ? (https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/CLL.html) How to verify an association of the factors with non-numeric data ?

Best regards,

Flora

**Comment by gtca** [comment]
Dear Flora,

The function converts covariates that are represented as factors to underlying numerical vectors as indicated by the printed message. 

This is how `as.numeric` conversion works for factors in R:

```r
> (x <- factor(c("a", "b")))
[1] a b
Levels: a b
> as.numeric(x)
[1] 1 2
```

**Comment by FloraMika** [comment]
Dear Danila,

Thank you very much for your answer.

It is still not clear to me. Which test do you use to find the association with each latent factor with a covariate which is not numeric ? 

I have a covariate (factor) with 3 levels... How is that handle ?

Best regards,

Flora

----- Original Message -----

**Comment by gtca** [comment]
This function computes Pearson correlation with `psych::corr.test` and `BH` correction for p-values.

That also works for factors with more than two levels:

```r
> x <- factor(rep(LETTERS[1:3], 2))
> cor(as.numeric(x), rep(1:3, 2))
[1] 1
```

One might consider one-hot encoding values instead as an alternative, e.g.:

```r
> as.matrix(model.matrix(~0 + x))
  xA xB xC
1  1  0  0
2  0  1  0
3  0  0  1
4  1  0  0
5  0  1  0
6  0  0  1
```

In general, that falls within the scope of the question of computing correlations for categorical variables with different approaches for it described [e.g. here](https://stats.stackexchange.com/a/112674).

**Comment by FloraMika** [comment]
Thank you very much for your answer.

Best regards,

Flora

----- Original Message -----
