### ISSUE TITLE
Error in 'get_data' due to "matrix_placeholder" object

### ISSUE THREAD

**Issue by oliviaAB** [bioFAM/MOFA2#81]
Hi,

I am trying to create some plots from my trained model, using the `plot_data_heatmap` function. I get the following error:

```r
> plot_data_heatmap(mofa2_output, view = "snps", factor = 1)
Error in data[[m]][[p]][as.character(features[[m]]), , drop = FALSE] : 
  object of type 'S4' is not subsettable
```

After a bit of investigation, the problem comes from the `get_data` function, specifically the line 344 of _get_methods.R_:

```r
data <- lapply(views, function(m) lapply(seq_len(length(data[[1]])), function(p) data[[m]][[p]][as.character(features[[m]]),,drop=FALSE]))
```

And it is due to `data[[m]][[p]]` being an object of class `matrix_placeholder` . Weirdly enough, when testing on another model, `plot_data_heatmap` works fine but `plot_data_scatter` gives the the same error as above. I tried to use the model from the tutorial but this gave me no errors.

I am using MOFA2 version 1.3.5 (just installed from Github). I'm happy to share the data privately if the error cannot be reproduced with a simple example.

Thank you for your help!

**Comment by gtca** [comment]
Hi @oliviaAB, I can reproduce this when loading the model with `load_model(..., load_data=FALSE)`.
In that case, the original data is not loaded, hence there's no data to plot a heatmap for. Loading it while setting `load_data=TRUE` works as expected.

Do you think this is a reason behind the issue in your case? If yes, we'll have to improve an error message here.

**Comment by oliviaAB** [comment]
Hi @gtca,

Thank you for your answer! This is interesting because I get the error when using the object created from run_mofa, rather than loading the model from the hdf5 model. But because I'm using the option `save_data = FALSE` in `run_mofa`, I guess with this option the data is also not saved in the trained model object. I tried by adding `save_data = TRUE` and everything works fine :)

Thanks a lot for your help!
