### ISSUE TITLE
Error in run_enrichment 

### ISSUE THREAD

**Issue by ProphetDarkland** [bioFAM/MOFA2#82]
Hi, 
I'm doing enrichment analysis with your tutorial at [https://raw.githack.com/bioFAM/MOFA2_tutorials/master/R_tutorials/GSEA.html](url). 
But when I ran this code:
```
enrichment.parametric <- run_enrichment(mofa, view = "RNA", factors = 1:4, feature.sets = MSigDB_v6.0_C5_human, sign = "negative", statistical.test = "parametric"
)
```
I got error messages as follows:
```
Error in data[[m]][[p]][as.character(features[[m]]), , drop = FALSE]: subscript out of bounds
Traceback:

1. run_enrichment(mofa, view = "RNA", factors = 1:4, feature.sets = MSigDB_v6.0_C5_human, 
 .     sign = "negative", statistical.test = "parametric")
2. get_data(object, views = view, as.data.frame = FALSE)
3. lapply(views, function(m) lapply(seq_len(length(data[[1]])), 
 .     function(p) data[[m]][[p]][as.character(features[[m]]), , 
 .         drop = FALSE]))
4. FUN(X[[i]], ...)
5. lapply(seq_len(length(data[[1]])), function(p) data[[m]][[p]][as.character(features[[m]]), 
 .     , drop = FALSE])
6. FUN(X[[i]], ...)
```
My mofa model is like this:
```
> mofa
 Trained MOFA with the following characteristics: 
 Number of views: 2 
 Views names: RNA ATAC 
 Number of features (per view): 2000 10000 
 Number of groups: 1 
 Groups names: group1 
 Number of samples (per group): 10412 
 Number of factors: 15 

```
I really don't know why this error occured. So if you could help me solve this problem, I would be really grateful.

**Comment by rargelaguet** [comment]
Hi @ProphetDarkland, 
There is probably a discrepancy between the feature names in the MOFA object (`features_names(mofa)`) and the Gene set matrix. Can you check?
If you can't figure it out feel free to send me your MOFA object via Slack channel (https://biofam.github.io/MOFA2/contact.html) and I'll have a look.

**Comment by ProphetDarkland** [comment]
Hi @rargelaguet ,
I checked the feature names in my MOFA object and there are indeed some feature names don't exist in the Gene set matrix. Is this the reason why I got the error?
And because I used a package to transfer the SYMBOL id to ENSEMBL id, there are also some feature names are NA. So how can I figure out this? Remove these feature names?
As I am not familiar with the MOFA object, I don't know how to remove features.

**Comment by rargelaguet** [comment]
I think the easiest option here is to use the [subset_features](https://rdrr.io/github/bioFAM/MOFA2/man/subset_features.html) function to keep only those that are present in the gene set matrix

**Comment by ProphetDarkland** [comment]
Thanks for the advice, but I don't know to write the parameter `features` in the function.
I have tried `subset_features(mofa, "RNA", c(1:10))` and got the error:
```
Warning message in subset_features(mofa, "RNA", c(1:10)):
“Removing features a posteriori is fine for an exploratory analysis, but we recommend removing them before training!”
Error in x[features, , drop = FALSE]: subscript out of bounds
Traceback:

1. subset_features(mofa, "RNA", c(1:10))
2. lapply(object@expectations$W, function(x) x[features, , drop = FALSE])
3. FUN(X[[i]], ...)
```
What does this error mean?

**Comment by rargelaguet** [comment]
could you send the MOFAobject via e-mail or slack channel (preferably) and I can have a look?

**Comment by ProphetDarkland** [comment]
OK.

**Comment by RomailRaouf** [comment]
@ProphetDarkland   
I am asking if you solve this error? as I face the same error. 
Thanks in advance
