### ISSUE TITLE
total explained variance is larger than 100

### ISSUE THREAD

**Issue by DongzeHE** [bioFAM/MOFA2#93]
Hello,

Could you please help me understand why the total explained variance is larger than 100? isn't it a percentage?  
<img width="569" alt="image" src="https://user-images.githubusercontent.com/32473855/175850558-f18fdda1-1859-4535-989c-77e1cde6175a.png">

**Comment by rargelaguet** [comment]
This is weird. Could you send the model via email (ricard.argelaguet@gmail.com) or slack channel (https://biofam.github.io/MOFA2/contact.html)
